[project]
name = "miprov2-with-evalutor-microservice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "huggingface-hub==0.26.2",
    "jupyter>=1.1.1",
    "pandas>=2.3.2",
    "requests>=2.32.5",
]
