apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.ragPlayground.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.ragPlayground.name }}
spec:
  replicas: {{ .Values.ragPlayground.replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.ragPlayground.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.ragPlayground.name }}
    spec:
      {{- if .Values.imagePullSecret.name }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret.name }}
      {{- end }}
      initContainers:
      - name: init-check-rag-playground
        imagePullPolicy: Always
        image: nvcr.io/nvidia/base/ubuntu:22.04_20240212
        command:
        - /bin/bash
        - -c
        - |
          apt update && apt install curl -y &&
          until curl -sf http://rag-server:8081/health/ ; do
            echo "Waiting for RAG server to be healthy..."
            sleep 10
          done
          echo "Grace time for all services to be ready after health check passes.."
          sleep 30
      containers:
      - name: {{ .Values.ragPlayground.name }}
        imagePullPolicy: {{ .Values.ragPlayground.image.pullPolicy }}
        image: {{ .Values.ragPlayground.image.repository }}:{{- .Values.ragPlayground.image.tag | default .Chart.AppVersion }}
        command:
        - python3.10
        - -m
        - frontend
        - --port
        - "8090"
        env:
          - name: APP_SERVERURL
            value: {{ .Values.ragPlayground.env.APP_SERVERURL | quote }}
          - name: APP_SERVERPORT
            value: {{ .Values.ragPlayground.env.APP_SERVERPORT | quote }}
          - name: APP_MODELNAME
            value: {{ .Values.ragPlayground.env.APP_MODELNAME | quote }}
        ports:
        - name: http
          containerPort: {{ .Values.ragPlayground.service.targetPort }}
          protocol: TCP
      {{- with .Values.ragPlayground.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ragPlayground.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ragPlayground.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ragPlayground.name }}
spec:
  type: {{ .Values.ragPlayground.service.type }}
  selector:
    app.kubernetes.io/name: {{ .Values.ragPlayground.name }}
{{- with .Values.ragPlayground.service.ports }}
  ports:
  {{- toYaml . | nindent 4 }}
{{- end }}
