- repoEntry:
    name:                  "nfd"
    url:                   "https://kubernetes-sigs.github.io/node-feature-discovery/charts"
  chartSpec:
    release:      "node-feature-discovery"
    chart:        "nfd/node-feature-discovery"
    namespace:        "node-feature-discovery"
    version:          "0.14.3"
  chartValues:
    kernelVersion: "{{ tpl .Values.runtime.kernelVersion }}" # {{ tpl .Values.chartValues.kernelVersion . }}
