repoEntry:
  name:                  "nvidia"
  url:                   "file:///home/zvonkok/helm-charts/nvidia"
  username:              ""
  password:              ""
  certFile:              ""
  keyFile:               ""
  caFile:                ""
  insecure_skip_tls_verify: false
  pass_credentials_all:    false

chartSpec:
  release:      "nvidia-kata"
  chart:        "nvidia/nvidia-kata"
  namespace:        "nvidia"
  valuesYaml:       ""
  version:          "0.3.0"
  createNamespace:  true
  disableHooks:     false
  replace:          true
  wait:             true
  waitForJobs:      true
  dependencyUpdate: false
  timeout:          10000000000
  generateName:     true
  NameTemplate:     ""
  atomic:           false
  skipCRDs:         false
  upgradeCRDs:      true
  subNotes:         false
  force:            false
  resetValues:      false
  reuseValues:      false
  recreate:         false
  maxHistory:       0
  cleanupOnFail:    false
  dryRun:           false
  #  postRenderer:     "setN"

chartValues:
  kernelVersion: "{{ tpl .Values.runtime.kernelVersion }}" # {{ tpl .Values.chartValues.kernelVersion . }}
