## Enable or disable Milvus Cluster mode
cluster:
  enabled: true
volumes: 
- name: custom
  emptyDir: {}
volumeMounts: 
- name: custom
  mountPath: /custom
etcd:
  replicaCount: 1
minio:
  mode: standalone
  resources:
    requests:
      memory: 100Mi
  persistence:
    size: 40Gi
pulsar:
  enabled: false
pulsarv3:
  enabled: true
  autorecovery:
    resources:
      requests:
        cpu: 0.01
        memory: 50Mi
  proxy:
    replicaCount: 1
    autoscaling:
      enabled: false
    resources:
      requests:
        memory: 64Mi
        cpu: 0.001
    configData:
      PULSAR_MEM: >
        -Xms64m -Xmx512m -XX:MaxDirectMemorySize=2048m
  bookkeeper:
    component: bookie
    replicaCount: 3
    resources:
      requests:
        memory: 64Mi
        cpu: 0.001
    volumes:
      persistence: true
      journal:
        size: 20Gi
      ledgers:
        size: 40Gi
    configData:
      PULSAR_MEM: >
        -Xms64m
        -Xmx4096m
        -XX:MaxDirectMemorySize=8192m
  zookeeper:
    replicaCount: 1
    resources:
      requests:
        memory: 64Mi
        cpu: 0.001
    configData:
      PULSAR_MEM: >
        -Xms64m -Xmx256m
  broker:
    replicaCount: 1
    resources:
      requests:
        memory: 64Mi
        cpu: 0.001
    configData:
      PULSAR_MEM: >
        -Xms64m -Xmx4096m -XX:MaxDirectMemorySize=8192m
