apiVersion: apps/v1
kind: Deployment
metadata:
  name: rag-server
  labels:
    app: rag-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: rag-server
  template:
    metadata:
      labels:
        app: rag-server
    spec:
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret.name }}
      {{- end }}
      containers:
        - name: rag-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - "uvicorn"
          - "src.server:app"
          - "--port"
          - "8081"
          - "--host"
          - "0.0.0.0"
          - "--workers"
          - "{{ .Values.server.workers }}"
          ports:
            - containerPort: 8081
          {{ if .Values.envVars }}
          env:
            {{- if .Values.envVars }}
            {{- range $k, $v := .Values.envVars }}
            - name: "{{ $k }}"
              value: "{{ $v }}"
            {{- end }}
            {{- end }}
          {{- end }}
          {{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: prompt-volume
              mountPath: /prompt.yaml
              subPath: prompt.yaml
      volumes:
        - name: prompt-volume
          configMap:
            name: prompt-config
            defaultMode: 0555