# SPDX-FileCopyrightText: Copyright (c) 2023-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Copyright (c) 2023-2025, NVIDIA CORPORATION.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


Common:
  model: nvidia/Llama-3.1-Nemotron-Nano-4B-v1.1
  max-model-len: 131072

Frontend:
  served_model_name: nvidia/Llama-3.1-Nemotron-Nano-4B-v1.1
  endpoint: dynamo.Processor.chat/completions
  port: 8000

Processor:
  router: round-robin
  common-configs: [model, max-model-len]


VllmWorker:
  router: random
  tensor-parallel-size: 1
  ServiceArgs:
    workers: 1
    resources:
      gpu: 1
  common-configs: [model, max-model-len]