from typing import Optional, List
# from langchain_core.pydantic_v1 import BaseModel, Field
from pydantic import BaseModel, Field

class Question(BaseModel):
    question: str = Field(description="The question generated by the LLM")

class Answer(BaseModel):
    answer: str = Field(description="The answer to the question generated by the LLM.")

class QuestionAnswerPair(BaseModel):
    question: Question
    answer: Answer

class SDGQA(BaseModel):
    sdgqa_pairs: List[QuestionAnswerPair] = Field(default_factory=list, description="List of Question and Answer pairs")

