{{ if .Values.model.ngcAPIKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ (first .Values.imagePullSecrets).name }}
  labels:
    {{- include "nim-llm.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "nim-llm.generatedImagePullSecret" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.model.ngcAPISecret }}
  labels:
    {{- include "nim-llm.labels" . | nindent 4 }}
type: Opaque
data:
  NGC_API_KEY: {{ .Values.model.ngcAPIKey | b64enc }}
{{ end }}
{{ if (and .Values.multiNode.enabled (not .Values.multiNode.existingSSHSecret) ) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nim-llm.fullname" . }}-ssh-pk
type: Opaque
data:
  private.key: |
    {{ genPrivateKey "rsa" | b64enc }}
{{ end }}
