---
{{- if .Values.metrics.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "nim-llm.fullname" . }}
  labels:
    {{- include "nim-llm.labels" . | nindent 4 }}
    {{- if .Values.metrics.serviceMonitor.additionalLabels }}
    {{- toYaml .Values.metrics.serviceMonitor.additionalLabels | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "nim-llm.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: {{ $.Values.model.legacyCompat | ternary "metrics" "http-openai" }}
{{- end -}}
