# permissions for end users to edit helmpipelines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: helmpipeline-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-trailblazer
    app.kubernetes.io/part-of: kube-trailblazer
    app.kubernetes.io/managed-by: kustomize
  name: helmpipeline-editor-role
rules:
- apiGroups:
  - package.nvidia.com
  resources:
  - helmpipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - package.nvidia.com
  resources:
  - helmpipelines/status
  verbs:
  - get
