# GitHub info on config.yml
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
# Set to 'false' if you only want the templates to be used. 
blank_issues_enabled: true

# When using discussions instead of Question issue templates,
# link that below to have it show up in the 'Submit Issue' page
contact_links:
  - name: Ask a Question
    url: https://github.com/jarmak-nv/rapids-repo-template/discussions
    about: Please ask any questions here.
