# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
version: "3.9"
services:
  chatbot-service:
    image: chatbot-service:latest
    build:
      context: .
      dockerfile: ./chatbot-service/fastapi/Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./chatbot-service/fastapi:/app
      - ./data:/app/data
    environment:
      - NGC_CLI_API_KEY=$NGC_CLI_API_KEY
      - NVIDIA_API_KEY=$NVIDIA_API_KEY
      - OPENAI_API_KEY=$OPENAI_API_KEY
  
  frontend-service:
    build:
      context: .
      dockerfile: ./frontend-service/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-service:/app

  lab-service:
    build:
      context: .
      dockerfile: ./lab-service/Dockerfile
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_TOKEN
      - NGC_CLI_API_KEY=$NGC_CLI_API_KEY
      - NVIDIA_API_KEY=$NVIDIA_API_KEY
      - OPENAI_API_KEY=$OPENAI_API_KEY
    volumes:
      - ./:/debug/
