llm:
  host: "127.0.0.1"
  port: 11434
  timeout: 360

proxy:
  port: 8002
  host: 0.0.0.0
  log_level: info
  cors:
    allow_origins:
      - "http://localhost:3000"
      - "http://127.0.0.1:3000"
      - "http://192.168.1.142:3000"
      - "http://192.168.1.119:3000"
    allow_credentials: true
    allow_methods: ["*"]
    allow_headers: ["*"]

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: proxy.log