# Use a base image with Python
FROM nvcr.io/nvidia/pytorch:23.05-py3 

# Set working directory
WORKDIR /app

#COPY notebooks
COPY ./notebooks/*.ipynb notebooks/

RUN mkdir -p /app/imgs

COPY ./notebooks/dataset.zip .
COPY ./notebooks/toy_data/* notebooks/toy_data/

COPY ./notebooks/imgs/* notebooks/imgs/

COPY ./integrations/langchain/llms/triton_trt_llm.py .

COPY ./integrations/langchain/llms/nv_aiplay.py .

COPY ./notebooks/requirements.txt .

# Run pip dependencies
RUN pip3 install -r requirements.txt

RUN apt-get update && apt-get install -y unzip wget git libgl1-mesa-glx libglib2.0-0

RUN pip3 install accelerate transformers==4.33.1 --upgrade

# Expose port 8888 for JupyterLab
EXPOSE 8888

# Start JupyterLab when the container runs
CMD ["jupyter", "lab", "--allow-root", "--ip=0.0.0.0","--NotebookApp.token=''", "--port=8888"]
