## Default settings
nvidia_api_key: "nvapi-****"
## Set these to required models endpoints from NVIDIA NGC 
llm_model: "mistralai/mixtral-8x7b-instruct-v0.1"
# Augmentation_model:
embedding_model: "NV-Embed-QA"

NIM: false
nim_model_name: "meta-llama3-8b-instruct"
nim_base_url: "http://localhost:8019/v1"
temperature: 0.1
top_p: 0.5
max_tokens: 1600

NREM: false
nrem_model_name: "NV-Embed-QA"
nrem_api_endpoint_url: "http://localhost:8084/v1"
nrem_truncate: "END"

file_delete_password: "oranpwd"
