apiVersion: package.nvidia.com/v1alpha1
kind: HelmPipeline
metadata:
  name: rag-llm-pipeline
spec:
  pipeline:
  - repoEntry:
      url: "file:///helm-charts/staging"
    chartSpec:
      chart:     "rag-llm-pipeline"
    chartValues: 
      triton:
        modelDirectory: "/zvonkok/model/llama2_13b_chat_hf_v1/"
      images:
        registry:
          ImagePullSecret:
            password: ${NVCR_TOKEN}
