apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    secureJsonData:
      token: 5g-lab-token
    jsonData:
      version: Flux
      organization: 5g-lab
      defaultBucket: 5g-metrics
      tlsSkipVerify: true 