
{{ if .Values.imagePullSecret.create -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "imagePullSecret" . | quote }}
{{- end }}

{{ if and .Values.ngcApiSecret.create -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ngcApiSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
data:
  NGC_CLI_API_KEY: {{ include "ngcApiSecret" . | quote }}
  NGC_API_KEY: {{ include "ngcApiSecret" . | quote }}
{{- end }}
