# SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

sensor:
    sample_rate: 1_000_000  # Sample rate of sensor (Hz)

network_rx:
    ip_addr: "0.0.0.0"
    dst_port: 5005
    l4_proto: "udp"
    batch_size: 47104  # Bytes to accumulate before emitting
    header_bytes: 8
    max_payload_size: 1472

pkt_format:
    log_period: 5  # Log bandwidth processed every N (seconds)

lowpassfilt:
    cutoff: 100_000  # Cutoff frequency of filter (Hz)
    numtaps: 101

resample:
    sample_rate_out: 16_000  # Sample rate required by Riva ASR (16KHz PCM)
    gain: 10.0

riva:
    src_lang_code: "en-US"
    uri: "localhost:50051"       # Riva server URI ("riva_speech_api_port" in riva/config.sh)
    automatic_punctuation: true
    verbatim_transcripts: false
    sample_rate: 16000           # Sample rate required by Riva ASR (16KHz PCM)