[build-system]
requires = [ "poetry-core",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "nv-mm-ingest-docs"
version = "0.0.1"
description = ""
authors = []
readme = "README.md"

[tool.langserve]
export_module = "nv_mm_ingest_docs"
export_attr = "chain"

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
langchain-core = "^0.3.15"
langchain-openai = ">=0.0.1"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.4"
fastapi = "^0.104.0"
sse-starlette = "^1.6.5"
