{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Avg Total (Input + Output)  words",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_tokens", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Avg Output Words",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "output_tokens", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Avg Input Words",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "input_tokens", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Avg words per chunk",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(avg_words_per_chunk)", "legendFormat": "__auto" }
   ]
  },
  { "title": "Usage metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Input tokens per request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "expr": "input_tokens", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Output tokens per request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    { "expr": "output_tokens", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total tokens per request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    { "expr": "total_tokens", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Avg words per chunk per request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    { "expr": "avg_words_per_chunk", "legendFormat": "__auto" }
   ]
  }
 ]
}