{{- if and (.Values.proxy.tls) (.Values.proxy.tls.enabled) }}

{{- if and (.Values.proxy.tls.crt) (.Values.proxy.tls.key) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.proxy.tls.secretName }}
  namespace: {{ .Release.Namespace }}
data:
  tls.crt: {{ .Values.proxy.tls.crt }}
  tls.key: {{ .Values.proxy.tls.key }}
type: kubernetes.io/tls
{{- end }}

{{- end -}}

