{{- if and .Values.queryCoordinator.enabled .Values.cluster.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "milvus.querycoord.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "milvus.labels" . | indent 4 }}
{{- if .Values.queryCoordinator.service.labels }}
{{ toYaml .Values.queryCoordinator.service.labels | indent 4 }}
{{- end }}
    component: "querycoord"
{{- with .Values.queryCoordinator.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: ClusterIP
  {{- if .Values.queryCoordinator.service.clusterIP }}
  clusterIP: {{ .Values.queryCoordinator.service.clusterIP }}
  {{- end }}
  ports:
    - name: querycoord
      port: {{ .Values.queryCoordinator.service.port }}
      protocol: TCP
      targetPort: querycoord
    {{- if .Values.metrics.enabled }}
    - name: metrics
      protocol: TCP
      port: 9091
      targetPort: metrics
    {{- end }}
  selector:
{{ include "milvus.matchLabels" . | indent 4 }}
    component: "querycoord"
{{- end }}