{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: {{ template "minio.pdb.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: minio
  labels:
    app: {{ template "minio.name" . }}
spec:
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ template "minio.name" . }}
{{- end }}
