replicaCount: 1

imagePullSecret:
  create: false
  name: "ngc-secret"
  registry: "nvcr.io"
  username: "$oauthtoken"
  password: ""

image:
  repository: nvcr.io/nvidia/blueprint/ingestor-server
  tag: "2.0.0"
  pullPolicy: IfNotPresent

server:
  workers: 1

envVars:
  # === Vector Store Configurations ===
  APP_VECTORSTORE_URL: "http://milvus:19530"
  APP_VECTORSTORE_NAME: "milvus"
  APP_VECTORSTORE_SEARCHTYPE: "dense"
  APP_VECTORSTORE_ENABLEGPUINDEX: "True"
  APP_VECTORSTORE_ENABLEGPUSEARCH: "True"
  COLLECTION_NAME: "multimodal_data"

  # === MinIO Configurations ===
  MINIO_ENDPOINT: "rag-minio:9000"
  MINIO_ACCESSKEY: "minioadmin"
  MINIO_SECRETKEY: "minioadmin"

  # === Embeddings Configurations ===
  APP_EMBEDDINGS_SERVERURL: "nemo-retriever-embedding-ms:8000"
  APP_EMBEDDINGS_MODELNAME: "nvidia/llama-3.2-nv-embedqa-1b-v2"
  APP_EMBEDDINGS_DIMENSIONS: "2048"

  # === NV-Ingest Configurations ===
  APP_NVINGEST_MESSAGECLIENTHOSTNAME: "rag-nv-ingest"
  APP_NVINGEST_MESSAGECLIENTPORT: "7670"

  # === NV-Ingest extraction configurations ===
  APP_NVINGEST_EXTRACTMETHOD: "pdfium"  # Method used for text extraction
  APP_NVINGEST_EXTRACTTEXT: "True"  # Enable text extraction
  APP_NVINGEST_EXTRACTTABLES: "True"  # Enable table extraction
  APP_NVINGEST_EXTRACTCHARTS: "True"  # Enable chart extraction
  APP_NVINGEST_EXTRACTIMAGES: "False"  # Enable image extraction
  APP_NVINGEST_TEXTDEPTH: "page"  # Extract text by "page" or "document"

  # === NV-Ingest caption configurations ===
  APP_NVINGEST_CAPTIONMODELNAME: "meta/llama-3.2-11b-vision-instruct"  # Model name for captioning
  APP_NVINGEST_CAPTIONENDPOINTURL: ""  # Endpoint URL for captioning model

  # === General ===
  ENABLE_CITATIONS: "True"
  LOGLEVEL: "INFO"

  # === NV-Ingest splitting configurations ===
  APP_NVINGEST_CHUNKSIZE: "1024"  # Size of chunks for splitting
  APP_NVINGEST_CHUNKOVERLAP: "150"  # Overlap size for chunks

# NV-Ingest
nv-ingest:
  imagePullSecrets:
    - name: "ngc-secret"
  ngcApiSecret:
    create: false
  ngcImagePullSecret:
    create: false
  image:
    repository: "nvcr.io/nvidia/nemo-microservices/nv-ingest"
    tag: "25.3.0"
  resources:
    limits:
      nvidia.com/gpu: 0
  envVars:
    AUDIO_GRPC_ENDPOINT: "audio:50051"
    AUDIO_INFER_PROTOCOL: "grpc"
    CUDA_VISIBLE_DEVICES: "0"
    MAX_INGEST_PROCESS_WORKERS: 16
    EMBEDDING_NIM_ENDPOINT: "http://nemo-retriever-embedding-ms:8000/v1"
    MESSAGE_CLIENT_HOST: "rag-redis-master"
    MINIO_INTERNAL_ADDRESS: rag-minio:9000
    MILVUS_ENDPOINT: "http://milvus:19530"
    MODEL_PREDOWNLOAD_PATH: "/workspace/models/"

  paddleocr-nim:
    image:
      repository: nvcr.io/nim/baidu/paddleocr
      tag: "1.2.0"
    imagePullSecrets:
    - name: ngc-secret

  nemoretriever-graphic-elements-v1:
    image:
      repository: nvcr.io/nim/nvidia/nemoretriever-graphic-elements-v1
      tag: "1.2.0"

  nemoretriever-page-elements-v2:
    image:
      repository: nvcr.io/nim/nvidia/nemoretriever-page-elements-v2
      tag: "1.2.0"

  nemoretriever-table-structure-v1:
    image:
      repository: nvcr.io/nim/nvidia/nemoretriever-table-structure-v1
      tag: "1.2.0"

  nim-vlm-text-extraction:
    image:
      repository: "nvcr.io/nim/nvidia/nemoretriever-parse"
      tag: "1.2"
    deployed: false

  nim-vlm-image-captioning:
    deployed: false

  nvidia-nim-llama-32-nv-embedqa-1b-v2:
    image:
      repository: nvcr.io/nim/nvidia/llama-3.2-nv-embedqa-1b-v2
      tag: "1.5.0"
    deployed: false
  milvus:
    image:
      all:
        repository: milvusdb/milvus
        tag: v2.5.3-gpu
        pullPolicy: IfNotPresent
    standalone:
      resources:
        limits:
          nvidia.com/gpu: 1
    fullnameOverride: "milvus"
