name: docs-preview-pr

on:
  workflow_run:
    workflows: [ docs-build ]
    types: [ completed ]
    branches-ignore: [ 'main' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  WF_ID: ${{ github.event.workflow_run.id }}

jobs:
  preview:
    uses: nvidia-merlin/.github/.github/workflows/docs-preview-pr-common.yaml@main